### ISSUE TITLE
Can the children/descendants loads up into array of the instance instead of returning the whole list?

### ISSUE THREAD

**Issue by SyedMSawaid** [1and1/acts_as_recursive_tree#19]
I mean can it form a tree like structure in memory? So instead of receiving this
```
[
  {
    id: 1,
    title: "First",
    parent: nil
  },
  {
    id: 2,
    title: "Second",
    parent: 1
  },
  {
    id: 3,
    title: "Third",
    parent: 1
  },
  {
    id: 4,
    title: "Fourth",
    parent: 3
  },
]
```

I receive this 👇
```
[
  {
    id: 1,
    title: "First",
    parent: nil,
    chidren: [
      {
        id: 2,
        title: "Second",
        parent: 1,
        children: []
      },
      {
        id: 3,
        title: "Third",
        parent: 1,
        children: [
          {
            id: 4,
            title: "Fourth",
            parent: 3
          },
        ]
      },
    ]
  },
]
```

**Comment by wollistik** [comment]
Hi @SyedMSawaid , this is currently not possible.

I had a quick look into the code of ActiveRecord::Associations::Preloader (this is internally called when you use `includes()` or `preload()`) and the actual implementation is very trivial. I could add a method to preload the tree on a model instance, if this suffices your use case. Then all you had to do would be to call

```ruby
node.preload_tree # fetches all descendants in one query and populates the children/parent associations 
```

This seems a very simple solution to me. Please give me your feedback!

**Comment by SyedMSawaid** [comment]
Yeah sure. I think 'has_ancestry` gem has some sort of method for this but I don't like how they store the parent - child relationship in the database.
Btw, how long will it take?

**Comment by wollistik** [comment]
I think I can free time this week to implement hit.
