### ISSUE TITLE
Add postgres cycle detection

### ISSUE THREAD

**Issue by wollistik** [1and1/acts_as_recursive_tree#22]
Postgres allows for automatic cycle detection in recursive queries (see https://www.postgresql.org/docs/current/queries-with.html). Check if this can be done with SQLite too and add it for at least postgres.

**Comment by wollistik** [comment]
Seems only postgres supports this:
https://modern-sql.com/caniuse/cycle_(recursion)

**Comment by kodai12** [comment]
Hi, I would like to use this gem if this feature is added. Can I expect any progress? (we are using Postgres)

**Comment by wollistik** [comment]
Hi @kodai12, sorry it took some time. I will release a new version with this feature today.
