### ISSUE TITLE
Is there any way I can either force reload the tree or its children, or remove a node from its children?

### ISSUE THREAD

**Issue by SyedMSawaid** [1and1/acts_as_recursive_tree#29]
I have a situation where I use `acts_as_list` along with `acts_as_recursive_tree`. I have a `Todo` which has a status. If all its children are done, then it should be considered done as well.

The problem is I have to recalculate the parent's status if I remove one node using `acts_as_list`'s `remove_from_list` method. Now I want to hard-refresh the tree but somehow it seems to have the previous state even though the change in database is reflected mid-operation.

**Comment by wollistik** [comment]
@SyedMSawaid sorry for the delay!
Simplest way would be to call `preload_tree` again. The complete hierarchy will then be loaded again from DB, so all changes made to child nodes will be updated in the tree.

**Comment by SyedMSawaid** [comment]
I found a fix to it by calling the reload method. For example, `children.reload`.

P.S. btw, is that you in the profile picture? You look like Christian Bale from American Psycho, an absolute chad. I hope I'm not the first one to say this.
